apiVersion: apps/v1
kind: Deployment
metadata:
  name: weather-dashboard
  labels:
    app: weather-dashboard
spec:
  replicas: 2
  selector:
    matchLabels:
      app: weather-dashboard
  template:
    metadata:
      labels:
        app: weather-dashboard
    spec:
      containers:
      - name: weather-dashboard
        image: gcr.io/carbon-inkwell-459718-n8/weather-dashboard:latest
        ports:
        - containerPort: 8080
        resources:
          requests:
            cpu: 50m    # Minimal CPU request
            memory: 64Mi # Minimal memory request
          limits:
            cpu: 200m    # Moderate CPU limit
            memory: 128Mi # Moderate memory limit
        env:
        - name: GOOGLE_APPLICATION_CREDENTIALS
          value: /var/secrets/google/key.json
        volumeMounts:
        - name: google-cloud-key
          mountPath: /var/secrets/google
      volumes:
      - name: google-cloud-key
        secret:
          secretName: weather-dashboard-key
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: weather-dashboard-hpa
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: weather-dashboard
  minReplicas: 1  # Keep minimum at 1 for continuous availability
  maxReplicas: 3  # Cap maximum at 3 for cost control
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 80  # Scale up only at high utilization
---
apiVersion: v1
kind: Service
metadata:
  name: weather-dashboard-service
spec:
  selector:
    app: weather-dashboard
  ports:
  - port: 80
    targetPort: 8080
  type: LoadBalancer